CREATE TABLE F_18_13_LOCATION
(
  LO_ID INTEGER NOT NULL,
  PRIMARY KEY (LO_ID),
  L_CITY VARCHAR(100),
  L_STATE VARCHAR(100)
);

CREATE TABLE F_18_13_ADVERTISEMENT
(
 AD_ID INTEGER NOT NULL,
 PRIMARY KEY (AD_ID),
 ADVERTISER_NAME VARCHAR(100),
 TYPE VARCHAR(100),
 ADNAME VARCHAR(100),
 RATE_WATCH FLOAT
);

CREATE TABLE F_18_13_RECORDING_LABELS -- 5 companies and name
(
  RNAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (RNAME)
);

CREATE TABLE F_18_13_ARTIST --5 artists for 5 genre total 25
(
  AR_ID INTEGER NOT NULL,
  PRIMARY KEY (AR_ID),
  AR_FNAME VARCHAR(100),
  AR_LNAME VARCHAR(100)
);

CREATE TABLE F_18_13_ALBUM -- 25 different albums
(
  A_ID INTEGER,
  PRIMARY KEY (A_ID),
  ANAME VARCHAR(100),
  GENRE VARCHAR(100),
  RNAME VARCHAR(100),
  RATE_STREAM FLOAT,
  S_MONTH INTEGER,
  S_YEAR INTEGER,
  FOREIGN KEY (RNAME) REFERENCES F_18_13_RECORDING_LABELS
   on delete cascade
);

CREATE TABLE F_18_13_LISTENER  -- 20 people
(
  L_ID INTEGER NOT NULL,
  PRIMARY KEY (L_ID),
  FNAME VARCHAR(100),
  LNAME VARCHAR(100),
  EMAIL VARCHAR(100),
  LO_ID INTEGER,
  FOREIGN KEY (LO_ID) REFERENCES F_18_13_LOCATION
   on delete cascade
);

CREATE TABLE F_18_13_TRACK  --25 tracks
(
  T_ID INTEGER NOT NULL,
  PRIMARY KEY (T_ID),
  TNAME VARCHAR(100),
  TMIN INTEGER,
  TSEC INTEGER,
  A_ID INTEGER,
  FOREIGN KEY (A_ID) REFERENCES F_18_13_ALBUM
  ON DELETE CASCADE
);

CREATE TABLE F_18_13_SERVER  --20
(
  S_ID INTEGER NOT NULL,
  PRIMARY KEY (S_ID),
  COST INTEGER,
  LO_ID INTEGER,
  FOREIGN KEY (LO_ID) REFERENCES F_18_13_LOCATION
  ON DELETE CASCADE
);

CREATE TABLE F_18_13_EMPLOYEE --20
(
  E_ID INTEGER NOT NULL,
  PRIMARY KEY (E_ID),
  SALARY INTEGER,
  LO_ID INTEGER,
  FOREIGN KEY (LO_ID) REFERENCES F_18_13_LOCATION
  ON DELETE CASCADE
);

CREATE TABLE F_18_13_I_GENRE
(
  INTERESTED_GENRE VARCHAR(100),
  L_ID INTEGER,
  PRIMARY KEY (INTERESTED_GENRE, L_ID),
  FOREIGN KEY (L_ID) REFERENCES F_18_13_LISTENER
  ON DELETE CASCADE
);

CREATE TABLE F_18_13_LISTENER_STREAMS_TRACK
(
  L_ID INTEGER NOT NULL,
  T_ID INTEGER NOT NULL,
  PRIMARY KEY (L_ID, T_ID),
  FOREIGN KEY (L_ID) REFERENCES F_18_13_LISTENER
  ON DELETE CASCADE,
  FOREIGN KEY (T_ID) REFERENCES F_18_13_TRACK
  ON DELETE CASCADE
);

CREATE TABLE F_18_13_LISTENER_WATCHES_AD
(
  L_ID INTEGER NOT NULL,
  AD_ID INTEGER NOT NULL,
  PRIMARY KEY (L_ID, AD_ID),
  FOREIGN KEY (L_ID) REFERENCES F_18_13_LISTENER
  ON DELETE CASCADE,
  FOREIGN KEY (AD_ID) REFERENCES F_18_13_ADVERTISEMENT
  ON DELETE CASCADE
);

CREATE TABLE F_18_13_ALBUM_HAS_ARTIST
(
  AR_ID INTEGER,
  A_ID INTEGER,
  PRIMARY KEY (AR_ID, A_ID),
  FOREIGN KEY (AR_ID) REFERENCES F_18_13_ARTIST
  ON DELETE CASCADE,
  FOREIGN KEY (A_ID) REFERENCES F_18_13_ALBUM
 ON DELETE CASCADE
);



CREATE TABLE F_18_13_T_DATE
(
  T_DATE DATE NOT NULL, --TDATE DATE NOT NULL
  L_ID INTEGER NOT NULL,
  T_ID INTEGER NOT NULL,
  PRIMARY KEY (T_DATE, L_ID, T_ID), --PRIMARY KEY (TDATE)
  FOREIGN KEY (L_ID) REFERENCES F_18_13_LISTENER
  ON DELETE cascade,
  FOREIGN KEY (T_ID) REFERENCES F_18_13_TRACK
  ON DELETE CASCADE
);

CREATE TABLE F_18_13_AD_DATE
(
  AD_DATE DATE NOT NULL, --ADDATE DATE NOT NULL
  L_ID INTEGER NOT NULL,
  AD_ID INTEGER NOT NULL,
  PRIMARY KEY (AD_DATE, L_ID, AD_ID),  --PRIMARY KEY (ADDATE)
  FOREIGN KEY (L_ID) REFERENCES F_18_13_LISTENER
  ON DELETE CASCADE,
  FOREIGN KEY (AD_ID) REFERENCES F_18_13_ADVERTISEMENT
  ON DELETE CASCADE
);
