SELECT DISTINCT L.LO_ID, L_CITY, L_STATE, SUM(TMIN + TSEC) AS H_S
  FROM F_18_13_LISTENER L, (SELECT *
    FROM F_18_13_LISTENER_STREAMS_TRACK L_S_T, F_18_13_TRACK T
    WHERE L_S_T.T_ID = T.T_ID) LTD, F_18_13_LOCATION LO
  WHERE L.L_ID = LTD.L_ID AND L.LO_ID = LO.LO_ID
  group by L.LO_ID, L_CITY, L_STATE
  ORDER BY SUM(TMIN + TSEC) DESC;
