SELECT L_D, L_CITY, L_STATE, S_ID, COST, E_ID, SALARY, SUM(COST + SALARY) AS OPCOST_PER_LOCATION
FROM      (SELECT DISTINCT S.LO_ID AS L_D, L_CITY, L_STATE, S_ID, COST
           FROM F_18_13_SERVER S, F_18_13_LOCATION L
           WHERE S.LO_ID = L.LO_ID) SL, F_18_13_EMPLOYEE E
WHERE SL.L_D = E.LO_ID
GROUP BY L_D, L_CITY, L_STATE, S_ID, COST, E_ID, SALARY;
